publish_interval: 0.05
joystick_fault_timeout: 3.0
vel_controller_name: /ssc/veh_controller
vehicle_platform: Lexus
wheel_base: 2.79
engage_speed_module: true
engage_steering_module: true
engage1_button: 6
engage2_button: 7 
park_button: 3
neutral_button: 2
drive_button: 0
reverse_button: 1
right_turn_button: 5
left_turn_button: 4 
speed_axes: 7
speed_up_sign: 1
speed_step: 1.0
# in mph
max_speed: 15.0
acceleration_limit: 2.0
deceleration_limit: 2.5
brake_axes: 2
brake_sign: 1
max_deceleration_limit: 4.0
steer_btn_axes: 6
steer_btn_sign: 1
steer_btn_step: 0.01
steering_axes: 3
steering_sign: 1.0
steering_exponent: 2.5
max_curvature: 0.12
max_curvature_rate: 0.1

test_quick_brake: false
quick_brake_speed: 0.0
joy_engage: false
rpm_dial_engage: false
hydraulics_engage: false
joy_sens: 0
rpm_dial_val: 0.0
hyd_in: 0.0
hyd_in_id: 0
beacon_in: false
horn_in: false